const actions = {
  GET_FETCH_CITIES: "GET_FETCH_CITIES",
  GET_CITY_SUCCESS: "GET_CITY_SUCCESS",
  GET_CITY_ERROR: "GET_CITY_ERROR",

  GET_FLIGHT_LIST: "GET_FLIGHT_LIST",
  GET_FLIGHT_LIST_SUCCESS: "GET_FLIGHT_LIST_SUCCESS",
  GET_FLIGHT_LIST_ERROR: "GET_FLIGHT_LIST_ERROR",
  RESET_FLIGHT_LIST: "RESET_FLIGHT_LIST",

  SET_BOOKING_DETAILS: "SET_BOOKING_DETAILS",
  CLEAR_BOOKING_DETAILS: "CLEAR_BOOKING_DETAILS",
};

export default actions;
